#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Load OpenFOAM v2506 environment
source ~/.bashrc
of2506

# Source tutorial run and clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

runApplication blockMesh

runApplication decomposePar

runApplication mpirun -np 8 LaserDPMFoam -parallel


#------------------------------------------------------------------------------
